# Generated by Django 6.0.6 on 2026-06-22 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('mac_address', models.CharField(max_length=17, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('floor', models.IntegerField(default=1)),
                ('is_online', models.BooleanField(default=False)),
                ('last_seen', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Relay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pin_number', models.IntegerField()),
                ('is_on', models.BooleanField(default=False)),
                ('power_rating_watts', models.IntegerField(default=0)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relays', to='iot.device')),
            ],
        ),
    ]
