# Generated by Django 6.0.6 on 2026-06-23 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ESPDevice',
            fields=[
                ('mac_address', models.CharField(help_text='Format: AA:BB:CC:DD:EE:FF', max_length=17, primary_key=True, serialize=False, unique=True)),
                ('alias', models.CharField(help_text='Alias for the ESP (e.g., First Floor ESP)', max_length=100)),
                ('device_type', models.CharField(choices=[('USER', 'General User / Student'), ('ADMIN', 'Admin Only')], default='USER', max_length=10)),
                ('floor', models.IntegerField(default=0, help_text='Floor number (0 for Ground, 1 for First...)')),
                ('location', models.CharField(blank=True, help_text='Exact location (e.g., Hall A, Lab 3)', max_length=100, null=True)),
                ('is_online', models.BooleanField(default=False)),
                ('connected_at', models.DateTimeField(blank=True, help_text='Timestamp of last connection', null=True)),
                ('disconnected_at', models.DateTimeField(blank=True, help_text='Timestamp of disconnection', null=True)),
            ],
            options={
                'verbose_name': 'ESP Device',
                'verbose_name_plural': 'ESP Devices',
            },
        ),
        migrations.CreateModel(
            name='Relay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(help_text='Relay alias (e.g., Right Wing Lights)', max_length=100)),
                ('pin_number', models.IntegerField(help_text='Physical GPIO Pin number connected to the relay')),
                ('mode', models.CharField(choices=[('MANUAL', 'Manual'), ('AUTO', 'Auto'), ('TIMER', 'Timer')], default='MANUAL', max_length=10)),
                ('state', models.CharField(choices=[('ON', 'On'), ('OFF', 'Off')], default='OFF', max_length=3)),
                ('esp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relays', to='iot.espdevice')),
            ],
            options={
                'verbose_name': 'Relay',
                'verbose_name_plural': 'Relays',
                'unique_together': {('esp', 'pin_number')},
            },
        ),
        migrations.CreateModel(
            name='PIRSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(help_text='Sensor alias (e.g., Corridor Motion Sensor)', max_length=100)),
                ('pin_number', models.IntegerField(help_text='Physical GPIO Pin number connected to the PIR')),
                ('last_triggered_at', models.DateTimeField(blank=True, help_text='Last time motion was detected', null=True)),
                ('esp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pir_sensors', to='iot.espdevice')),
                ('linked_relay', models.ForeignKey(blank=True, help_text='The relay to trigger automatically when motion is detected', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_pirs', to='iot.relay')),
            ],
            options={
                'verbose_name': 'PIR Sensor',
                'verbose_name_plural': 'PIR Sensors',
                'unique_together': {('esp', 'pin_number')},
            },
        ),
    ]
