# Generated by Django 6.0.6 on 2026-06-24 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='espdevice',
            name='temperature',
            field=models.FloatField(blank=True, help_text='Current temperature', null=True),
        ),
    ]
